language: python
sudo: required
dist: focal
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
env:
  - FALCON=1.4.1
  - FALCON=2.0.0
  - FALCON=3.0.1
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
install:
  - pip install falcon==$FALCON
  - pip install ".[test]" .
script: pytest --cov=./falcon_crossorigin
after_success:
  - codecov
